// Generated by scripts/generate-www-deny-middleware.py — do not edit.
const EXACT = new Set(["/OFFERINGS_LOCKED.md","/PROJECT_BOUNDARIES_LOCKED.md","/ROUTING_CARD.md","/railway.toml","/governance/OPS_LIVE_STATUS_LOCKED.json","/governance/LAW_STACK.json","/governance/FACTORY_CATALOG.json","/governance/STRIPE_CATALOG.json","/governance/CAPABILITY_TIER_CATALOG.json","/governance/strategy-alignment-map.json","/governance/PUBLIC_OUTPUT_DENYLIST.json","/governance/VALIDATOR_REGISTRY.json","/governance/NODE_CATALOG.json","/governance/ROUTE_INVENTORY.json","/governance/FREEMIUM_POLICY_LOCKED_v1.md","/governance/README.md","/docs/LOCAL_DEV.md","/docs/ROADMAP.md","/docs/LEGAL.md","/docs/MARKET_ENTRY_30_DAY.md"]);
const PREFIXES = ["/.agents/","/.cursor/","/.sina-agent/","/_archive/","/Noetfield-All-Documents/","/L0-law/","/L1-operational/","/L2-knowledge/","/L3-external/","/apps/","/data/","/docs/ops/","/docs/platform/","/docs/references/","/docs/spec/","/docs/SOURCE_OF_TRUTH/","/entry/","/governance/oas-engine/","/governance/golden-edge-synth/","/governance/alignment-scoring/","/governance-console/","/infra/","/infrastructure/","/ops/","/os/","/packages/","/platform/","/reports/","/scripts/","/services/ai-runtime/","/services/aml-trace/","/services/copilot-governance/","/services/events/","/services/factories/","/services/governance/","/services/graph/","/services/identity/","/services/inspectors/","/services/ledger/","/services/legal-review/","/services/signals/","/services/trust-brief/","/services/workflow/","/tests/","/var/"];
const GOV_PROXY = {"enabled":true,"origins":{"/workspace":"https://gov-sandbox-web-production.up.railway.app","/tle":"https://gov-sandbox-api-production.up.railway.app","/connectors":"https://gov-sandbox-api-production.up.railway.app","/audit":"https://gov-sandbox-api-production.up.railway.app","/evidence":"https://gov-sandbox-api-production.up.railway.app","/api/v1/sandbox":"https://gov-sandbox-api-production.up.railway.app"}};

function isDenied(pathname) {
  if (EXACT.has(pathname)) return true;
  for (const raw of PREFIXES) {
    const base = raw.endsWith("/") ? raw.slice(0, -1) : raw;
    if (pathname === base || pathname === raw) return true;
    const withSlash = raw.endsWith("/") ? raw : `${raw}/`;
    if (pathname.startsWith(withSlash)) return true;
  }
  return false;
}

function matchGovProxy(pathname) {
  if (!GOV_PROXY.enabled) return null;
  const sorted = Object.keys(GOV_PROXY.origins).sort((a, b) => b.length - a.length);
  for (const prefix of sorted) {
    if (pathname === prefix || pathname.startsWith(`${prefix}/`)) {
      return { prefix, origin: GOV_PROXY.origins[prefix] };
    }
  }
  return null;
}

const PUBLIC_SECURITY_HEADERS = {
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
  "Content-Security-Policy":
    "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self' https:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; script-src 'self'; connect-src 'self' https://www.noetfield.com https://noetfield.com https://platform.noetfield.com https://api.noetfield.com https://scan.noetfield.com; upgrade-insecure-requests",
};

function applyPublicSecurityHeaders(response) {
  const headers = new Headers(response.headers);
  for (const [key, value] of Object.entries(PUBLIC_SECURITY_HEADERS)) {
    headers.set(key, value);
  }
  const contentType = (headers.get("content-type") || "").toLowerCase();
  if (contentType.includes("text/html")) {
    headers.delete("Access-Control-Allow-Origin");
    headers.delete("Access-Control-Allow-Credentials");
    headers.delete("Access-Control-Allow-Methods");
    headers.delete("Access-Control-Allow-Headers");
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

async function proxyGovRequest(context, match) {
  const req = context.request;
  const url = new URL(req.url);
  const target = new URL(url.pathname + url.search, match.origin);
  const headers = new Headers(req.headers);
  headers.delete("host");
  const init = { method: req.method, headers, redirect: "manual" };
  if (req.method !== "GET" && req.method !== "HEAD") {
    init.body = req.body;
  }
  return applyPublicSecurityHeaders(await fetch(target.toString(), init));
}

export async function onRequest(context) {
  const pathname = new URL(context.request.url).pathname;
  const gov = matchGovProxy(pathname);
  if (gov) {
    return proxyGovRequest(context, gov);
  }

  if (!isDenied(pathname)) {
    return applyPublicSecurityHeaders(await context.next());
  }

  const notFoundUrl = new URL("/404.html", context.request.url);
  if (context.env?.ASSETS?.fetch) {
    const asset = await context.env.ASSETS.fetch(notFoundUrl);
    if (asset && asset.ok) {
      return applyPublicSecurityHeaders(
        new Response(asset.body, {
          status: 404,
          headers: {
            "content-type": asset.headers.get("content-type") || "text/html; charset=utf-8",
            "cache-control": "no-store",
          },
        }),
      );
    }
  }

  return applyPublicSecurityHeaders(
    new Response("Not found", {
      status: 404,
      headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" },
    }),
  );
}
