#!/usr/bin/env bash
# Start governance-console API + Next dev server (foreground — keeps running until Ctrl+C).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="$ROOT/governance-console/backend"
FRONTEND="$ROOT/governance-console/frontend"
DB_FILE="$BACKEND/.dev_governance.db"
ENV_FILE="$ROOT/.dev-cognitive-dashboard.env"
API_PID=""

export DATABASE_URL="${DATABASE_URL:-sqlite:///${DB_FILE}}"

pick_port() {
  local candidates=("$@")
  local p
  for p in "${candidates[@]}"; do
    if ! lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "$p"
      return 0
    fi
  done
  echo "No free port in: ${candidates[*]}" >&2
  exit 1
}

cleanup() {
  if [[ -n "$API_PID" ]] && kill -0 "$API_PID" 2>/dev/null; then
    kill "$API_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

WEB_PORT="$(pick_port "${COGNITIVE_DASHBOARD_PORT:-3000}" 3100 3200 3300)"
if [[ -n "${COGNITIVE_DASHBOARD_API_PORT:-}" ]]; then
  API_PORT="$COGNITIVE_DASHBOARD_API_PORT"
else
  API_PORT="$(pick_port 8000 8001 8002)"
fi
export NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-http://127.0.0.1:${API_PORT}}"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/dev-cognitive-dashboard.sh — source this for the active URLs
export COGNITIVE_DASHBOARD_PORT=$WEB_PORT
export NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
COGNITIVE_DASHBOARD_URL=http://localhost:${WEB_PORT}/cognitive-dashboard
EOF

echo "Starting API on 127.0.0.1:${API_PORT} …"
cd "$BACKEND"
python3 -m pip install -q -r requirements.txt
python3 -m uvicorn main:app --host 0.0.0.0 --port "$API_PORT" &
API_PID=$!

echo "Waiting for API health …"
deadline=$((SECONDS + 60))
until curl -sf "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; do
  if (( SECONDS >= deadline )); then
    echo "API did not become healthy on port ${API_PORT}" >&2
    exit 1
  fi
  sleep 1
done

cd "$FRONTEND"
if [[ ! -d node_modules ]]; then
  echo "Installing frontend dependencies …"
  npm install
fi

echo ""
echo "=============================================="
echo " Cognitive dashboard (dev)"
echo "   http://localhost:${WEB_PORT}/cognitive-dashboard"
echo "   http://127.0.0.1:${WEB_PORT}/cognitive-dashboard"
echo " API docs: http://127.0.0.1:${API_PORT}/docs"
echo " Port file: ${ENV_FILE}"
echo " Press Ctrl+C to stop API + web"
echo "=============================================="
echo ""

# Foreground Next — script stays alive; works on Mac/Linux terminals.
exec npx next dev --port "$WEB_PORT" --hostname 0.0.0.0
