#!/usr/bin/env python3
"""Generate Cloudflare Pages _redirects from governance/www-pages-routes.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTES = ROOT / "governance" / "www-pages-routes.json"
PROXY_CFG = ROOT / "data" / "nf-www-gov-proxy-v1.json"
OUT = ROOT / "_redirects"


def _gov_proxy_rules() -> list[str]:
    # External-origin proxy is handled by functions/_middleware.js (Cloudflare Pages
    # _redirects cannot 200-proxy to third-party origins). Keep config read for parity.
    if not PROXY_CFG.is_file():
        return []
    try:
        cfg = json.loads(PROXY_CFG.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    if not cfg.get("enabled"):
        return []
    web = str(cfg.get("gov_web_origin") or "").rstrip("/")
    api = str(cfg.get("gov_api_origin") or "").rstrip("/")
    if not web or not api:
        return []
    return [
        "# Governance workspace proxy: functions/_middleware.js (nf-www-gov-proxy-v1 enabled)",
    ]


def main() -> int:
    data = json.loads(ROUTES.read_text(encoding="utf-8"))
    lines: list[str] = [
        "# Generated by scripts/generate-cf-redirects.py — do not edit.",
        "# Host redirects are handled by Cloudflare Worker/zone routes.",
        "# Denylist 404s are handled by functions/_middleware.js.",
    ]

    lines.extend(_gov_proxy_rules())

    for rule in data.get("rewrites") or []:
        source = str(rule.get("source") or "").strip()
        dest = str(rule.get("destination") or "").strip()
        if source and dest:
            lines.append(f"{source} {dest} 200")

    for rule in data.get("redirects") or []:
        source = str(rule.get("source") or "").strip()
        dest = str(rule.get("destination") or "").strip()
        status = int(rule.get("statusCode") or 302)
        has_rules = rule.get("has") or []
        if has_rules:
            # Pages _redirects does not accept absolute/host-matching sources.
            # Host behavior belongs in the zone Worker or a zone redirect rule.
            continue
        if source and dest:
            # Pages _redirects does not accept 404 as a redirect status. The
            # generated Pages middleware enforces these deny rules fail-closed.
            if status == 404:
                continue
            if dest == "/404":
                dest = "/404.html"
            lines.append(f"{source} {dest} {status}")

    text = "\n".join(lines) + "\n"
    if OUT.is_file() and OUT.read_text(encoding="utf-8") == text:
        print(f"ok unchanged {_redirects_name()}")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {_redirects_name()} ({len(lines) - 1} rules)")
    return 0


def _redirects_name() -> str:
    return "_redirects"


if __name__ == "__main__":
    raise SystemExit(main())
