#!/usr/bin/env python3
"""Generate Cloudflare Pages _middleware.js from PUBLIC_OUTPUT_DENYLIST.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DENYLIST = ROOT / "governance" / "PUBLIC_OUTPUT_DENYLIST.json"
OUT = ROOT / "functions" / "_middleware.js"


def _deny_sets(data: dict) -> tuple[list[str], list[str]]:
    exact = list(dict.fromkeys(str(p) for p in data.get("exact_paths", [])))
    prefixes = list(dict.fromkeys(str(p) for p in data.get("prefix_paths", [])))
    return exact, prefixes


def main() -> int:
    data = json.loads(DENYLIST.read_text(encoding="utf-8"))
    exact, prefixes = _deny_sets(data)
    exact_json = json.dumps(exact, separators=(",", ":"))
    prefix_json = json.dumps(prefixes, separators=(",", ":"))

    source = f"""// Generated by scripts/generate-www-deny-middleware.py — do not edit.
const EXACT = new Set({exact_json});
const PREFIXES = {prefix_json};

function isDenied(pathname) {{
  if (EXACT.has(pathname)) return true;
  for (const raw of PREFIXES) {{
    const base = raw.endsWith("/") ? raw.slice(0, -1) : raw;
    if (pathname === base || pathname === raw) return true;
    const withSlash = raw.endsWith("/") ? raw : `${{raw}}/`;
    if (pathname.startsWith(withSlash)) return true;
  }}
  return false;
}}

export async function onRequest(context) {{
  const pathname = new URL(context.request.url).pathname;
  if (!isDenied(pathname)) {{
    return context.next();
  }}

  const notFoundUrl = new URL("/404.html", context.request.url);
  if (context.env?.ASSETS?.fetch) {{
    const asset = await context.env.ASSETS.fetch(notFoundUrl);
    if (asset && asset.ok) {{
      return new Response(asset.body, {{
        status: 404,
        headers: {{
          "content-type": asset.headers.get("content-type") || "text/html; charset=utf-8",
          "cache-control": "no-store",
        }},
      }});
    }}
  }}

  return new Response("Not found", {{
    status: 404,
    headers: {{ "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" }},
  }});
}}
"""

    if OUT.is_file() and OUT.read_text(encoding="utf-8") == source:
        print("ok unchanged functions/_middleware.js")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(source, encoding="utf-8")
    print(f"wrote functions/_middleware.js ({len(exact)} exact, {len(prefixes)} prefixes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
