#!/usr/bin/env python3
"""Generate Cloudflare Pages _redirects from vercel.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERCEL = ROOT / "vercel.json"
PROXY_CFG = ROOT / "data" / "nf-www-gov-proxy-v1.json"
OUT = ROOT / "_redirects"


def _gov_proxy_rules() -> list[str]:
    if not PROXY_CFG.is_file():
        return []
    try:
        cfg = json.loads(PROXY_CFG.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    if not cfg.get("enabled"):
        return []
    web = str(cfg.get("gov_web_origin") or "").rstrip("/")
    api = str(cfg.get("gov_api_origin") or "").rstrip("/")
    if not web or not api:
        return []
    rules: list[str] = [
        "# Governance workspace proxy (nf-www-gov-proxy-v1)",
        f"/workspace/* {web}/workspace/:splat 200",
        f"/workspace {web}/workspace 200",
        f"/tle/* {api}/tle/:splat 200",
        f"/tle {api}/tle 200",
        f"/connectors/* {api}/connectors/:splat 200",
        f"/connectors {api}/connectors 200",
        f"/audit/* {api}/audit/:splat 200",
        f"/audit {api}/audit 200",
        f"/evidence/* {api}/evidence/:splat 200",
        f"/api/v1/sandbox/* {api}/api/v1/sandbox/:splat 200",
        f"/api/v1/sandbox {api}/api/v1/sandbox 200",
    ]
    return rules


def main() -> int:
    data = json.loads(VERCEL.read_text(encoding="utf-8"))
    lines: list[str] = [
        "# Generated by scripts/generate-cf-redirects.py — do not edit.",
    ]

    lines.extend(_gov_proxy_rules())

    for rule in data.get("rewrites") or []:
        source = str(rule.get("source") or "").strip()
        dest = str(rule.get("destination") or "").strip()
        if source and dest:
            lines.append(f"{source} {dest} 200")

    for rule in data.get("redirects") or []:
        source = str(rule.get("source") or "").strip()
        dest = str(rule.get("destination") or "").strip()
        status = int(rule.get("statusCode") or 302)
        has_rules = rule.get("has") or []
        if has_rules:
            host = ""
            for item in has_rules:
                if isinstance(item, dict) and item.get("type") == "host":
                    host = str(item.get("value") or "")
            if host and dest:
                lines.append(f"https://{host}{source} {dest} {status}")
            continue
        if source and dest:
            if dest == "/404":
                dest = "/404.html"
            lines.append(f"{source} {dest} {status}")

    text = "\n".join(lines) + "\n"
    if OUT.is_file() and OUT.read_text(encoding="utf-8") == text:
        print(f"ok unchanged {_redirects_name()}")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {_redirects_name()} ({len(lines) - 1} rules)")
    return 0


def _redirects_name() -> str:
    return "_redirects"


if __name__ == "__main__":
    raise SystemExit(main())
